# Generated by Django 4.0 on 2022-08-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('식당 및 카페', '식당 및 카페'), ('전시 및 체험공간', '전시 및 체험공간'), ('제로웨이스트 샵', '제로웨이스트 샵'), ('도시 재생 및 친환경 건출물', '도시 재생 및 친환경 건출물'), ('복합 문화 공간', '복합 문화 공간'), ('녹색 공간', '녹색 공간'), ('그 외', '그 외')], max_length=30)),
                ('vegan_category', models.CharField(blank=True, choices=[('비건', '비건'), ('락토', '락토'), ('오보', '오보'), ('페스코', '페스코'), ('폴로', '폴로'), ('그 외', '그 외')], max_length=10)),
                ('tumblur_category', models.BooleanField(blank=True)),
                ('reusable_con_category', models.BooleanField(blank=True)),
                ('pet_category', models.BooleanField(blank=True)),
                ('mon_hours', models.CharField(max_length=50)),
                ('tues_hours', models.CharField(max_length=50)),
                ('wed_hours', models.CharField(max_length=50)),
                ('thurs_hours', models.CharField(max_length=50)),
                ('fri_hours', models.CharField(max_length=50)),
                ('sat_hours', models.CharField(max_length=50)),
                ('sun_hours', models.CharField(max_length=50)),
                ('etc_hours', models.TextField(max_length=500)),
                ('place_review', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('place_like_cnt', models.PositiveIntegerField(default=0)),
                ('rep_pic', models.URLField(blank=True, max_length=300)),
                ('short_cur', models.TextField(blank=True, max_length=500)),
                ('left_coordinate', models.FloatField(blank=True)),
                ('right_coordinate', models.FloatField(blank=True)),
                ('phone_num', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SNSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SNSUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('snstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.snstype')),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.URLField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
