# Generated by Django 4.0 on 2022-07-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='place/%Y%m%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('식당 및 카페', '식당 및 카페'), ('전시 및 체험공간', '전시 및 체험공간'), ('제로웨이스트 샵', '제로웨이스트 샵'), ('도시 재생 및 친환경 건출물', '도시 재생 및 친환경 건출물'), ('복합 문화 공간', '복합 문화 공간'), ('녹색 공간', '녹색 공간'), ('그 외', '그 외')], max_length=30)),
                ('vegan_category', models.CharField(blank=True, choices=[('비건', '비건'), ('락토', '락토'), ('오보', '오보'), ('페스코', '페스코'), ('폴로', '폴로')], max_length=10)),
                ('reusable_category', models.CharField(blank=True, choices=[('텀블러 할인', '텀블러 할인'), ('용기내', '용기내')], max_length=10)),
                ('pet_category', models.BooleanField(blank=True, default=False, null=True)),
                ('mon_hours', models.CharField(max_length=50)),
                ('tues_hours', models.CharField(max_length=50)),
                ('wed_hours', models.CharField(max_length=50)),
                ('thurs_hours', models.CharField(max_length=50)),
                ('fri_hours', models.CharField(max_length=50)),
                ('sat_hours', models.CharField(max_length=50)),
                ('sun_hours', models.CharField(max_length=50)),
                ('place_review', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('sub_address', models.CharField(max_length=200)),
                ('place_like_cnt', models.PositiveIntegerField(default=0)),
                ('rep_pic', models.ImageField(blank=True, null=True, upload_to='place_rep/%Y%m%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SNSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'SNS Type',
            },
        ),
        migrations.CreateModel(
            name='SNSUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_url', models.URLField(null=True)),
                ('sns_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sns_url_place', to='places.place')),
                ('sns_type_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sns_type_forurl', to='places.snstype')),
            ],
        ),
    ]
