# Generated by Django 4.0 on 2022-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.ManyToManyField(blank=True, related_name='place', to='places.PlaceType'),
        ),
    ]
