# Generated by Django 4.0 on 2022-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='fri_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='mon_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='pet_category',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='reusable_con_category',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='sat_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='sun_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='thurs_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='tues_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='tumblur_category',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='wed_hours',
            field=models.CharField(max_length=100),
        ),
    ]
