# Generated by Django 4.0 on 2022-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_cur',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='pet_category',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='rep_pic',
            field=models.ImageField(blank=True, upload_to='place_rep/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='vegan_category',
            field=models.CharField(blank=True, choices=[('비건', '비건'), ('락토', '락토'), ('오보', '오보'), ('페스코', '페스코'), ('폴로', '폴로'), ('그 외', '그 외')], max_length=10),
        ),
    ]
