# Generated by Django 4.0 on 2022-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_short_cur_alter_place_pet_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rep_pic',
            field=models.ImageField(default='', upload_to='place_rep/%Y%m%d/'),
        ),
    ]
