# Generated by Django 4.0 on 2022-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_fri_hours_alter_place_mon_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
