# Generated by Django 4.0 on 2022-09-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='etc_hours',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='placephoto',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place'),
        ),
    ]
