# Generated by Django 4.0 on 2022-07-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_rep_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='reusable_category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_address',
        ),
        migrations.AddField(
            model_name='place',
            name='reusable_con_category',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='tumblur_category',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
