# Generated by Django 4.0 on 2022-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_etc_hours_alter_placephoto_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='left_coordinate',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='right_coordinate',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='distance',
        ),
        migrations.AlterField(
            model_name='place',
            name='rep_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='placephoto',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
