# Generated by Django 4.0 on 2022-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_reusable_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pet_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='reusable_con_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='tumblur_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
