# Generated by Django 4.0 on 2022-10-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_left_coordinate_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsurl',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_sns_url', to='places.place'),
            preserve_default=False,
        ),
    ]
