# Generated by Django 4.0 on 2022-07-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_pet_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='left_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='right_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
