# Generated by Django 4.0 on 2022-10-10 03:42

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_snsurl_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placephoto',
            name='image',
            field=models.ImageField(default='place_image.png', upload_to=places.models.get_upload_path),
        ),
    ]
