# Generated by Django 4.0 on 2022-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_etc_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.URLField(default=0, max_length=3000),
            preserve_default=False,
        ),
    ]
