# Generated by Django 4.0 on 2022-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rep_pic',
            field=models.URLField(default='', max_length=3000),
        ),
    ]
