# Generated by Django 4.0 on 2022-11-26 10:21

from django.db import migrations, models
import django.db.models.deletion
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_categorycontent_visitorreview_visitorreviewcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to=places.models.image_upload_path)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.visitorreview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
