# Generated by Django 4.0 on 2022-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_reviewphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewphoto',
            old_name='place',
            new_name='review',
        ),
    ]
