# Generated by Django 4.0 on 2022-11-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_category'),
        ('places', '0011_rename_place_reviewphoto_review'),
    ]

    operations = [
    ]
