# Generated by Django 4.0 on 2022-11-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_merge_20221128_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorreviewcategory',
            name='category_choice',
            field=models.ManyToManyField(related_name='category', to='places.VisitorReview'),
        ),
    ]
