# Generated by Django 4.0 on 2023-03-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_social_provider'),
        ('places', '0014_alter_categorycontent_category_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorReview',
            new_name='PlaceVisitorReview',
        ),
        migrations.RenameModel(
            old_name='VisitorReviewCategory',
            new_name='PlaceVisitorReviewCategory',
        ),
        migrations.RenameModel(
            old_name='ReviewPhoto',
            new_name='PlaceVisitorReviewPhoto',
        ),
    ]
