# Generated by Django 4.0 on 2023-05-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_rename_visitorreview_placevisitorreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
    ]
