# Generated by Django 4.0 on 2022-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://sasm-bucket.s3.ap-northeast-2.amazonaws.com/users/SASM+user+profile+image.png', upload_to='profile/%Y%m%d/'),
        ),
    ]
