# Generated by Django 4.0 on 2022-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='http://www.w3.org/2000/svg', null=True, upload_to='profile/%Y%m%d/'),
        ),
    ]
