# Generated by Django 4.0 on 2022-08-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
        ('users', '0002_user_code'),
    ]

    operations = [
    ]
