# Generated by Django 4.0 on 2023-03-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_social_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_authorized',
        ),
    ]
