# Generated by Django 4.0 on 2023-04-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_admin_user_is_authorized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_authorized',
            new_name='is_verified',
        ),
    ]
