# Generated by Django 4.0 on 2023-09-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('forest', '0007_delete_forestusercategory'),
        ('users', '0010_user_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semi_categories',
            field=models.ManyToManyField(blank=True, related_name='semi_category', to='forest.SemiCategory'),
        ),
    ]
