version: "3"

services:
  web:
    image: 851125685257.dkr.ecr.ap-northeast-2.amazonaws.com/sasm:${TAG}
    container_name: web
    command: gunicorn sasmproject.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: sasmproject.settings.prod # prod.py > .env 파일에 있는 값들을 환경변수로 설정
    env_file:
      - .env # .github/workflows/deploy.yml에서 만든 env 파일에 의존
    expose:
      - 8000
    # entrypoint:
    #   - sh
    #   - config/docker/entrypoint.prod.sh
  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - web
