# Generated by Django 4.0 on 2023-06-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_alter_forestphoto_forest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestphoto',
            name='forest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='forest.forest'),
        ),
    ]
