# Generated by Django 4.0 on 2023-06-07 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_user_introduction'),
        ('forest', '0003_alter_forestphoto_forest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=1000)),
                ('like_cnt', models.PositiveIntegerField(default=0)),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forest.forest')),
                ('likeuser_set', models.ManyToManyField(blank=True, related_name='liked_forest_comments', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forest_comments', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
