# Generated by Django 4.0 on 2023-06-29 07:21

from django.db import migrations, models
import forest.models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0004_forestcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest',
            name='rep_pic',
            field=models.ImageField(default='forest_rep_pic.png', upload_to=forest.models.get_forest_rep_pic_upload_path),
        ),
    ]
