# Generated by Django 4.0 on 2023-09-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_introduction'),
        ('forest', '0005_forest_rep_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestUserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('semi_category', models.ManyToManyField(related_name='usersemicategory', to='forest.SemiCategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercategory', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
