# Generated by Django 4.0 on 2023-09-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0006_forestusercategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForestUserCategory',
        ),
    ]
