# Generated by Django 4.0 on 2022-08-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('story_review', models.CharField(max_length=200)),
                ('story_like_cnt', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(max_length=100)),
                ('preview', models.CharField(blank=True, max_length=150)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('story_url', models.URLField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='places.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('image', models.URLField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
