# Generated by Django 4.0 on 2022-07-08 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='StoryLikeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.paragraph'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='stories.story'),
        ),
    ]
