# Generated by Django 4.0 on 2022-08-31 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='StoryLikeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
