# Generated by Django 4.0 on 2022-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='short_cur',
        ),
        migrations.AddField(
            model_name='story',
            name='preview',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
