# Generated by Django 4.0 on 2022-08-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_short_cur_story_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
