# Generated by Django 4.0 on 2022-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_tag_alter_comment_options_alter_story_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='stories.Tag'),
        ),
    ]
