# Generated by Django 4.0 on 2022-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyphoto',
            name='story',
        ),
        migrations.AlterField(
            model_name='storyphoto',
            name='image',
            field=models.ImageField(default='story_image.png', upload_to=''),
        ),
    ]
