# Generated by Django 4.0 on 2022-03-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_tag_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='writer',
        ),
    ]
