# Generated by Django 4.0 on 2022-09-30 11:56

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_remove_storyphoto_story_alter_storyphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_url',
        ),
        migrations.AlterField(
            model_name='storyphoto',
            name='image',
            field=models.ImageField(default='story_image.png', upload_to=stories.models.get_upload_path),
        ),
    ]
