# Generated by Django 4.0 on 2022-10-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_remove_story_story_url_alter_storyphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='rep_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
