# Generated by Django 4.0 on 2022-03-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_rename_user_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='location',
        ),
    ]
