# Generated by Django 4.0 on 2022-10-08 01:40

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_story_rep_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='rep_pic',
            field=models.ImageField(default='story_rep_pic.png', upload_to=stories.models.get_upload_path),
        ),
    ]
