# Generated by Django 4.0 on 2023-04-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_rename_visitorreview_placevisitorreview_and_more'),
        ('stories', '0011_story_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='places.place'),
        ),
    ]
