# Generated by Django 4.0 on 2023-05-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_rename_visitorreview_placevisitorreview_and_more'),
        ('stories', '0012_story_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyphoto',
            name='story',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stories.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='address',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
