# Generated by Django 4.0 on 2023-05-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_rename_visitorreview_placevisitorreview_and_more'),
        ('stories', '0013_storyphoto_story_alter_story_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='places.place'),
        ),
    ]
