# Generated by Django 4.0 on 2023-05-11 01:21

from django.db import migrations, models
import django.db.models.deletion
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_alter_story_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('map', models.ImageField(default='story_map_photo.png', upload_to=stories.models.get_upload_path)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_photos', to='stories.story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
