# Generated by Django 4.0 on 2023-07-19 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0015_storymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycomment',
            name='like_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='liked_story_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
