# Generated by Django 4.0 on 2023-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.UniqueConstraint(fields=('name', 'post'), name='post_can_have_hashtag_with_unique_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='user_can_like_post_only_once_constraint'),
        ),
    ]
