# Generated by Django 4.0 on 2023-01-06 15:05

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentPhoto',
            new_name='PostCommentPhoto',
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='image',
            field=models.ImageField(default='post_image.png', upload_to=community.models.get_upload_path),
        ),
    ]
