# Generated by Django 4.0 on 2023-01-11 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_sdp'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('게시판 성격에 부적절함', '게시판 성격에 부적절함'), ('음란물/불건전한 만남 및 대화', '음란물/불건전한 만남 및 대화'), ('사칭/사기성 게시글', '사칭/사기성 게시글'), ('욕설/비하', '욕설/비하'), ('낚시/도배성 게시글', '낚시/도배성 게시글'), ('상업적 광고 및 판매', '상업적 광고 및 판매')], max_length=30)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.postcomment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comment_reports', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('게시판 성격에 부적절함', '게시판 성격에 부적절함'), ('음란물/불건전한 만남 및 대화', '음란물/불건전한 만남 및 대화'), ('사칭/사기성 게시글', '사칭/사기성 게시글'), ('욕설/비하', '욕설/비하'), ('낚시/도배성 게시글', '낚시/도배성 게시글'), ('상업적 광고 및 판매', '상업적 광고 및 판매')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='comment_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports', to='users.user'),
        ),
    ]
