# Generated by Django 4.0 on 2023-01-30 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_post_post_likeuser_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
