# Generated by Django 4.0 on 2023-01-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_posthashtag_post_can_have_hashtag_with_unique_name_constraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContentStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('styled_content', models.TextField(max_length=50000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='board',
            name='post_content_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_boards', to='community.postcontentstyle'),
        ),
    ]
