# Generated by Django 4.0 on 2023-01-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_postcontentstyle_board_post_content_style'),
        ('community', '0003_rename_comment_postcommentphoto_post_comment_and_more'),
    ]

    operations = [
    ]
