# Generated by Django 4.0 on 2023-02-01 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_merge_20230129_1526'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posthashtag',
            name='post_can_have_hashtag_with_unique_name_constraint',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_cnt',
        ),
        migrations.RemoveField(
            model_name='posthashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posthashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='community.Post'),
        ),
    ]
