# Generated by Django 4.0 on 2023-02-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_posthashtag_post_can_have_hashtag_with_unique_name_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlike',
            name='user_can_like_post_only_once_constraint',
        ),
    ]
