# Generated by Django 4.0 on 2023-02-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_postlike_user_can_like_post_only_once_constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
