# Generated by Django 4.0 on 2023-02-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_delete_postlike'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.UniqueConstraint(fields=('name',), name='post_can_have_hashtag_with_unique_name_constraint'),
        ),
    ]
