# Generated by Django 4.0 on 2023-04-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_postcommentreport_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_cnt',
        ),
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.CharField(default='없음', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='없음', max_length=200),
        ),
        migrations.CreateModel(
            name='PostPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='community.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
