# Generated by Django 4.0 on 2023-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_remove_post_comment_cnt_post_keyword_post_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keyword',
            field=models.CharField(blank=True, default='없음', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default='없음', max_length=200),
        ),
    ]
