# Generated by Django 4.0 on 2023-04-30 23:54

import curations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curations', '0002_remove_curation_rep_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('map', models.ImageField(default='curation_map_photo.png', upload_to=curations.models.get_upload_path)),
                ('curation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_photos', to='curations.curation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
